title = "Gnarly Void"
description = "Tuning the Silence Into A Harmony of Matter"
base_url = "https://gnarlyvoid.com"

compile_sass = false
build_search_index = false

[[taxonomies]]
name = "tags"
feed = true

generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = false

[extra]
